// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app1.db.Models;

public partial class Discount
{
    public string Discounttype { get; set; }

    public string StorId { get; set; }

    public short? Lowqty { get; set; }

    public short? Highqty { get; set; }

    public decimal Discount1 { get; set; }

    public virtual Store Stor { get; set; }
}