// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app1.db.Models;

public partial class PubInfo
{
    public string PubId { get; set; }

    public byte[] Logo { get; set; }

    public string PrInfo { get; set; }

    public virtual Publisher Pub { get; set; }
}