// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleLinq.Models.Pubs;

public partial class discount
{
    public string discounttype { get; set; }

    public string stor_id { get; set; }

    public short? lowqty { get; set; }

    public short? highqty { get; set; }

    public decimal discount1 { get; set; }

    public virtual store stor { get; set; }
}