// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleLinq.Models.Pubs;

public partial class job
{
    public short job_id { get; set; }

    public string job_desc { get; set; }

    public byte min_lvl { get; set; }

    public byte max_lvl { get; set; }

    public virtual ICollection<employee> employees { get; set; } = new List<employee>();
}