// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleLinq.Models.Pubs;

public partial class sale
{
    public string stor_id { get; set; }

    public string ord_num { get; set; }

    public DateTime ord_date { get; set; }

    public short qty { get; set; }

    public string payterms { get; set; }

    public string title_id { get; set; }

    public virtual store stor { get; set; }

    public virtual title title { get; set; }
}