// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleLinq.Models.Pubs;

public partial class store
{
    public string stor_id { get; set; }

    public string stor_name { get; set; }

    public string stor_address { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip { get; set; }

    public virtual ICollection<sale> sales { get; set; } = new List<sale>();
}